import { z } from "zod";

export const L2_ARTIFACT_TYPES = [
  "QuestionFrame",
  "ResearchBrief",
  "HypothesisSet",
  "EvidencePlan",
  "QueryContract",
  "GroundingPackage",
  "SemanticQuery",
  "LogicalPlan",
  "SqlArtifact",
  "GateReceipt",
  "ExecutionPermit",
  "ValidationReceipt",
  "ExecutionReceipt",
  "QueryEvidence",
  "DataProfile",
  "AnalysisProgram",
  "DerivedAnalysisEvidence",
  "AnalysisCompletionReceipt",
  "AtomicClaim",
  "EvidenceRelation",
  "ObligationExecutionDecision",
  "EvidenceCheckReceipt",
  "SupportDecision",
  "HypothesisAssessment",
  "CoverageState",
  "ResearchStopDecision",
  "ReportManifest",
  "AnalysisReport",
  "ReportProjectionReceipt",
  "EvidenceGateReceipt",
  "ReportReadyCertificate",
  "ReadinessRevocationReceipt",
] as const;

export const DEFERRED_ARTIFACT_TYPES = [
  "ExperimentPlan",
  "ExperimentResult",
  "ResultCertificate",
  "ObservationSpec",
  "DiscoveryCandidate",
  "DiscoveryReceipt",
  "CausalQuestion",
  "IdentificationPlan",
  "CausalEstimate",
  "IdentificationCertificate",
] as const;

export const SYSTEM_ARTIFACT_TYPES = [
  "AnalysisInputMaterializationReceipt",
  "TabularImportReceipt",
  "ArtifactExportReceipt",
  "ArtifactWorkspaceDocument",
  "SensitiveExecutionArtifact",
  "ReleaseManifest",
  "EvalCase",
  "EvalRegistryAssignment",
  "EvalRun",
  "OracleVerdictReceipt",
  "ScoreCard",
  "ModelCertificationReceipt",
  "ProviderTaskArtifact",
  "ProviderResponseArtifact",
  "ProviderStaleMarkerRecoveryReceipt",
  "ExternalAgentAuditReceipt",
  "ResourceAdmissionReceipt",
  "FixtureMutationRecord",
  "MetamorphicFixtureReceipt",
  "MetamorphicOracleReceipt",
  "ResultOracleReceipt",
  "SandboxResult",
  "SandboxExecutionReceipt",
  "BenchmarkAdapterReceipt",
  "SemanticSourceBundle",
  "SemanticGraphCandidate",
  "SemanticRelease",
  "SchemaSnapshot",
  "PolicyReceipt",
  "AgentDataProjectionReceipt",
  "KnowledgeRetrievalReceipt",
  "EvalReleaseDecision",
  "BenchmarkManifest",
  "BenchmarkDatasetSnapshot",
  "BenchmarkImportReceipt",
  "EvalBatchRun",
  "EvalCaseRun",
  "EvalAttempt",
  "ReflectionReceipt",
  "BatchScoreCard",
] as const;

export const KNOWN_ARTIFACT_TYPES = [
  ...L2_ARTIFACT_TYPES,
  ...DEFERRED_ARTIFACT_TYPES,
  ...SYSTEM_ARTIFACT_TYPES,
] as const;

export const l2ArtifactTypeSchema = z.enum(L2_ARTIFACT_TYPES);
export const knownArtifactTypeSchema = z.enum(KNOWN_ARTIFACT_TYPES);
export type L2ArtifactType = z.infer<typeof l2ArtifactTypeSchema>;
export type KnownArtifactType = z.infer<typeof knownArtifactTypeSchema>;
