-- Diagnostic only. Run on an explicitly identified, idle physical scratch clone.
-- No formal Run, receipt, message or activation is created; every fixture rolls back.
-- Required psql variables: expected_cluster_name, expected_system_identifier,
-- source_attempt_id, manifest_banks (JSON array generated by Contracts), test_begin.
begin;
set local statement_timeout='120000ms';
select set_config('falcon24.test_cluster',:'expected_cluster_name',true),
  set_config('falcon24.test_system_id',:'expected_system_identifier',true),
  set_config('falcon24.test_source_attempt',:'source_attempt_id',true);
create temp table falcon24_test_banks on commit drop as
  select value bank from jsonb_array_elements(:'manifest_banks'::jsonb);
select set_config('data_agent.app_id','00000000-0000-4000-8000-00000000da01',true),
  set_config('data_agent.tenant_id','00000000-0000-4000-8000-00000000e124',true),
  set_config('data_agent.environment','local',true),
  set_config('data_agent.principal_id','00000000-0000-4000-8000-00000000e125',true),
  set_config('data_agent.role','owner',true),
  set_config('data_agent.deployment_id','00000000-0000-4000-8000-000000000001',true),
  set_config('app.semantic_domain','falcon24',true);

do $guard$
begin
  if session_user<>'postgres' or current_user<>'postgres'
    or current_setting('cluster_name')<>current_setting('falcon24.test_cluster')
    or current_setting('cluster_name') not like 'falcon24-e17-%'
    or (select system_identifier::text from pg_control_system())
      <>current_setting('falcon24.test_system_id')
    or not exists(select 1 from app_data_agent.falcon24_four_layer_gate_attempts
      where attempt_id=current_setting('falcon24.test_source_attempt')::uuid
        and authority_epoch='E17' and status='FAILED')
    or exists(select 1 from app_data_agent.falcon24_four_layer_gate_attempts
      where status in('READY','RUNNING','FINALIZING'))
    or (select count(*) from falcon24_test_banks)<>10
  then raise exception 'RESOURCE_SNAPSHOT_TEST_BINDING_INVALID'; end if;
end
$guard$;

-- Test the actual public begin RPC and its replay, not a reimplementation.
\if :test_begin
do $begin_cases$
declare bank jsonb;manifest jsonb;command jsonb;result jsonb;replay jsonb;cases integer:=0;
begin
  for bank in select b.bank from falcon24_test_banks b loop
    begin
      select manifest_document-'manifest_hash' into strict manifest
        from app_data_agent.falcon24_four_layer_gate_attempts
        where attempt_id=current_setting('falcon24.test_source_attempt')::uuid;
      manifest:=manifest||jsonb_build_object('attempt_id',gen_random_uuid(),
        'schema_version',bank->>'schema_version','turns',bank->'turns');
      manifest:=manifest||jsonb_build_object('manifest_hash',
        app_data_agent.u2_canonical_sha256(manifest));
      command:=jsonb_build_object('schema_version','falcon24-four-layer-gate-begin@1.0.0',
        'manifest',manifest);
      command:=command||jsonb_build_object('command_hash',app_data_agent.u2_canonical_sha256(command));
      set local role data_agent_backend;
      result:=app_data_agent.begin_falcon24_four_layer_gate(command);
      replay:=app_data_agent.begin_falcon24_four_layer_gate(command);
      reset role;
      if result is distinct from replay or result#>>'{attempt,status}'<>'READY'
        or result#>>'{attempt,manifest_document,schema_version}'<>bank->>'schema_version'
      then raise exception 'RESOURCE_SNAPSHOT_BEGIN_REPLAY_FAILED'; end if;
      manifest:=jsonb_set(manifest-'manifest_hash','{turns,0,question}','"Tampered diagnostic question"');
      manifest:=manifest||jsonb_build_object('manifest_hash',app_data_agent.u2_canonical_sha256(manifest));
      command:=jsonb_build_object('schema_version','falcon24-four-layer-gate-begin@1.0.0','manifest',manifest);
      command:=command||jsonb_build_object('command_hash',app_data_agent.u2_canonical_sha256(command));
      begin
        set local role data_agent_backend;
        perform app_data_agent.begin_falcon24_four_layer_gate(command);
        raise exception 'RESOURCE_SNAPSHOT_TAMPERED_BANK_ACCEPTED';
      exception when sqlstate '22023' then
        if sqlerrm<>'FALCON24_FOUR_LAYER_MANIFEST_INVALID' then raise; end if;
      end;
      reset role;
      raise exception using errcode='Z0001',message='ROLLBACK_DIAGNOSTIC_CASE';
    exception when sqlstate 'Z0001' then null;
    end;
    cases:=cases+1;
  end loop;
  raise notice 'RESOURCE_SNAPSHOT_BEGIN_REPLAY_PASS versions=%',cases;
end
$begin_cases$;
\endif

create function pg_temp.test_resource_claim(
  manifest_version text,previous_version bigint,current_version bigint,
  expected_error text,variation text default 'base',scenario_index integer default 1)
returns void language plpgsql as $test$
declare fixture app_data_agent.falcon24_four_layer_gate_attempts%rowtype;
  previous_turn app_data_agent.falcon24_four_layer_gate_turns%rowtype;
  planned_turn app_data_agent.falcon24_four_layer_gate_turns%rowtype;
  conversation app_data_agent.qa_conversations%rowtype;
  command jsonb;result jsonb;replay jsonb;source_id uuid;
begin
  source_id:=current_setting('falcon24.test_source_attempt')::uuid;
  begin
    select * into strict fixture from app_data_agent.falcon24_four_layer_gate_attempts
      where attempt_id=source_id;
    fixture.attempt_id:=gen_random_uuid();
    fixture.manifest_document:=fixture.manifest_document||jsonb_build_object(
      'attempt_id',fixture.attempt_id,'schema_version',manifest_version);
    fixture.manifest_hash:=app_data_agent.u2_canonical_sha256(fixture.manifest_document-'manifest_hash');
    fixture.manifest_document:=fixture.manifest_document||jsonb_build_object('manifest_hash',fixture.manifest_hash);
    fixture.status:='READY';fixture.current_layer:='L4';fixture.next_turn_ordinal:=9+scenario_index;
    fixture.attempt_version:=1;fixture.first_failure_turn_ordinal:=null;
    fixture.first_failure_run_id:=null;fixture.first_failure_code:=null;
    fixture.terminal_receipt_hash:=null;fixture.terminal_receipt:=null;
    insert into app_data_agent.falcon24_four_layer_gate_attempts select (fixture).*;

    select * into strict previous_turn from app_data_agent.falcon24_four_layer_gate_turns
      where attempt_id=source_id and turn_ordinal=9;
    if previous_turn.status<>'PASSED' then raise exception 'RESOURCE_SNAPSHOT_SOURCE_NOT_PASSED'; end if;
    select * into strict conversation from app_data_agent.qa_conversations
      where conversation_id=previous_turn.conversation_id;
    conversation.conversation_id:=gen_random_uuid();
    conversation.resource_version:=current_version;
    conversation.title:='Rollback-only resource snapshot fixture';
    insert into app_data_agent.qa_conversations select (conversation).*;

    -- Seed only fresh diagnostic rows. Never update sealed source rows or disable guards.
    select * into strict previous_turn from app_data_agent.falcon24_four_layer_gate_turns
      where attempt_id=source_id and turn_ordinal=8+scenario_index;
    previous_turn.attempt_id:=fixture.attempt_id;
    previous_turn.conversation_id:=conversation.conversation_id;
    previous_turn.conversation_resource_version:=previous_version;
    previous_turn.run_id:=gen_random_uuid();
    previous_turn.claim_command_hash:=app_data_agent.u2_canonical_sha256(to_jsonb(previous_turn.run_id));
    previous_turn.status:=case when variation='previous-not-passed' then 'QA_PASSED' else 'PASSED' end;
    previous_turn.completed_at:=clock_timestamp();
    previous_turn.business_receipt:=null;previous_turn.business_receipt_hash:=null;
    previous_turn.qa_ui_receipt:=null;previous_turn.qa_ui_receipt_hash:=null;
    previous_turn.trace_ui_receipt:=null;previous_turn.trace_ui_receipt_hash:=null;
    previous_turn.terminal_receipt:=null;previous_turn.terminal_receipt_hash:=null;
    insert into app_data_agent.falcon24_four_layer_gate_turns select (previous_turn).*;
    select * into strict planned_turn from app_data_agent.falcon24_four_layer_gate_turns
      where attempt_id=source_id and turn_ordinal=9+scenario_index;
    if planned_turn.status<>'PLANNED' then raise exception 'RESOURCE_SNAPSHOT_SOURCE_NOT_PLANNED'; end if;
    planned_turn.attempt_id:=fixture.attempt_id;
    insert into app_data_agent.falcon24_four_layer_gate_turns select (planned_turn).*;
    command:=jsonb_build_object('schema_version','falcon24-four-layer-turn-claim@1.0.0',
      'attempt_id',fixture.attempt_id,'turn_ordinal',planned_turn.turn_ordinal,
      'conversation_id',conversation.conversation_id,'conversation_resource_version',current_version,
      'run_id',gen_random_uuid(),'idempotency_key','diagnostic-resource-snapshot',
      'expected_attempt_version',1,'expected_turn_version',planned_turn.turn_version);
    case variation
      when 'different-conversation' then
        conversation.conversation_id:=gen_random_uuid();
        insert into app_data_agent.qa_conversations select (conversation).*;
        command:=jsonb_set(command,'{conversation_id}',to_jsonb(conversation.conversation_id));
      when 'stale-version' then
        command:=jsonb_set(command,'{conversation_resource_version}',to_jsonb(current_version+1));
      when 'cas-conflict' then command:=jsonb_set(command,'{expected_attempt_version}','2');
      when 'reused-run' then command:=jsonb_set(command,'{run_id}',to_jsonb(previous_turn.run_id));
      when 'wrong-ordinal' then command:=jsonb_set(command,'{turn_ordinal}','14');
      else null;
    end case;
    command:=command||jsonb_build_object('command_hash',app_data_agent.u2_canonical_sha256(command));
    begin
      set local role data_agent_backend;
      result:=app_data_agent.claim_falcon24_four_layer_gate_turn(command);
      replay:=app_data_agent.claim_falcon24_four_layer_gate_turn(command);
      reset role;
      if expected_error is not null then raise exception 'RESOURCE_SNAPSHOT_EXPECTED_REJECTION_%',expected_error; end if;
      if result is distinct from replay or result#>>'{turn,status}'<>'CLAIMED'
        or (result#>>'{turn,conversation_resource_version}')::bigint<>current_version
        or result#>>'{attempt,status}'<>'RUNNING'
        or result#>>'{attempt,attempt_version}'<>'2'
      then raise exception 'RESOURCE_SNAPSHOT_CLAIM_RESULT_INVALID'; end if;
      command:=jsonb_set(command-'command_hash','{run_id}',to_jsonb(gen_random_uuid()));
      command:=command||jsonb_build_object('command_hash',app_data_agent.u2_canonical_sha256(command));
      begin
        set local role data_agent_backend;
        perform app_data_agent.claim_falcon24_four_layer_gate_turn(command);
        raise exception 'RESOURCE_SNAPSHOT_CHANGED_REPLAY_ACCEPTED';
      exception when sqlstate '55000' then
        if sqlerrm<>'FALCON24_FOUR_LAYER_REPLAY_MISMATCH' then raise; end if;
      end;
      reset role;
    exception when others then
      if expected_error is null or (sqlerrm<>expected_error and sqlstate<>expected_error) then raise; end if;
    end;
    raise exception using errcode='Z0001',message='ROLLBACK_DIAGNOSTIC_CASE';
  exception when sqlstate 'Z0001' then null;
  end;
end
$test$;

do $claim_cases$
declare version integer;schema_version text;cases integer:=0;
begin
  for version in 1..10 loop
    schema_version:='falcon24-four-layer-gate-manifest@'||version||'.0.0';
    perform pg_temp.test_resource_claim(schema_version,1,1,
      case when version=10 then null else 'FALCON24_FOUR_LAYER_CONVERSATION_MISMATCH' end);
    perform pg_temp.test_resource_claim(schema_version,1,2,null);
    perform pg_temp.test_resource_claim(schema_version,2,1,'FALCON24_FOUR_LAYER_CONVERSATION_MISMATCH');
    cases:=cases+3;
  end loop;
  schema_version:='falcon24-four-layer-gate-manifest@10.0.0';
  perform pg_temp.test_resource_claim(schema_version,1,1,null,'base',2);
  perform pg_temp.test_resource_claim(schema_version,1,1,'FALCON24_FOUR_LAYER_CONVERSATION_MISMATCH','previous-not-passed');
  perform pg_temp.test_resource_claim(schema_version,1,1,'FALCON24_FOUR_LAYER_CONVERSATION_MISMATCH','different-conversation');
  perform pg_temp.test_resource_claim(schema_version,1,1,'FALCON24_FOUR_LAYER_CONVERSATION_MISMATCH','stale-version');
  perform pg_temp.test_resource_claim(schema_version,1,1,'FALCON24_FOUR_LAYER_VERSION_CONFLICT','cas-conflict');
  perform pg_temp.test_resource_claim(schema_version,1,1,'23505','reused-run');
  perform pg_temp.test_resource_claim(schema_version,1,1,'FALCON24_FOUR_LAYER_NOT_FOUND','wrong-ordinal');
  raise notice 'RESOURCE_SNAPSHOT_CLAIM_MATRIX_PASS cases=%',cases+7;
end
$claim_cases$;
rollback;
