import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { semanticSourceBundleSchema } from "../packages/contracts/src/index.ts";

const output = resolve("infra/agenticdatabench/ecommerce-v1/semantic/ecommerce-source-bundle.json");
const datasourceId = "00000000-0000-4000-8000-00000000ec01";
const physicalColumnName = (columnId: string): string => {
  const columnName = columnId.split(".")[1];
  if (!columnName) throw new Error(`Invalid governed column identity: ${columnId}`);
  return columnName;
};
const grain = (id: string, granularity: "atomic" | "month" = "atomic") => ({
  grain_id: `ecommerce-${id}-grain@1`,
  description: `${id} 业务粒度`,
  granularity,
});
const unit = (dimension: "count" | "currency" | "ratio" | "duration" | "other") => ({
  unit_id: `ecommerce-${dimension}-unit@1`,
  description: `E-commerce ${dimension} unit`,
  dimension,
  base_unit: null,
  conversion_factor: null,
});
const timeDomain = {
  time_domain_id: "ecommerce-order-time@1",
  description: "Olist 订单购买时间，UTC 存储",
  calendar: "gregorian" as const,
  timezone: "UTC",
  min_time: "2016-09-01",
  max_time: "2018-10-31",
};
const metricDefinitions = [
  ["order-count", "订单量", "fact_order", "order_id", "count_distinct", "count"],
  ["customer-count", "下单客户数", "fact_order", "customer_id", "count_distinct", "count"],
  [
    "delivery-delay-avg",
    "平均配送延迟天数",
    "fact_order",
    "delivery_delay_days",
    "avg",
    "duration",
  ],
  [
    "delivery-delay-max",
    "最大配送延迟天数",
    "fact_order",
    "delivery_delay_days",
    "max",
    "duration",
  ],
  ["item-count", "商品件数", "fact_order_item", "order_item_id", "count", "count"],
  ["gmv-brl", "成交总额 GMV", "fact_order_item", "price_brl", "sum", "currency"],
  ["item-price-avg", "平均商品成交价", "fact_order_item", "price_brl", "avg", "currency"],
  ["item-price-min", "最低商品成交价", "fact_order_item", "price_brl", "min", "currency"],
  ["item-price-max", "最高商品成交价", "fact_order_item", "price_brl", "max", "currency"],
  ["freight-total", "运费总额", "fact_order_item", "freight_value_brl", "sum", "currency"],
  ["freight-avg", "平均运费", "fact_order_item", "freight_value_brl", "avg", "currency"],
  ["seller-count", "活跃卖家数", "fact_order_item", "seller_id", "count_distinct", "count"],
  ["product-count", "成交商品数", "fact_order_item", "product_id", "count_distinct", "count"],
  ["payment-total", "支付总额", "fact_payment", "payment_value_brl", "sum", "currency"],
  ["payment-count", "支付笔数", "fact_payment", "payment_sequence", "count", "count"],
  ["installments-avg", "平均分期数", "fact_payment", "installments", "avg", "count"],
  ["installments-max", "最大分期数", "fact_payment", "installments", "max", "count"],
  ["review-count", "评价数", "fact_review", "review_row_id", "count", "count"],
  ["review-score-avg", "平均评价分", "fact_review", "review_score", "avg", "ratio"],
  ["review-score-min", "最低评价分", "fact_review", "review_score", "min", "ratio"],
  ["review-score-max", "最高评价分", "fact_review", "review_score", "max", "ratio"],
  ["amazon-review-count", "Amazon 评价数", "fact_amazon_review", "review_row_id", "count", "count"],
  ["amazon-rating-avg", "Amazon 平均评分", "fact_amazon_review", "rating", "avg", "ratio"],
  [
    "amazon-product-count",
    "Amazon 被评商品数",
    "fact_amazon_review",
    "asin",
    "count_distinct",
    "count",
  ],
  ["amazon-price-avg", "Amazon 平均标价", "dim_amazon_product", "price_usd", "avg", "currency"],
  ["ebay-listing-count", "eBay 刊登数", "dim_ebay_listing", "listing_id", "count", "count"],
  ["ebay-price-avg", "eBay 平均价格", "dim_ebay_listing", "price_usd", "avg", "currency"],
  ["ebay-ram-avg", "eBay 平均内存容量", "dim_ebay_listing", "ram_gb", "avg", "other"],
  ["ebay-ssd-avg", "eBay 平均固态容量", "dim_ebay_listing", "ssd_gb", "avg", "other"],
  [
    "state-pair-orders",
    "州对月订单量",
    "fact_delivery_state_month",
    "total_orders",
    "sum",
    "count",
  ],
  [
    "state-pair-delay-avg",
    "州对月平均延迟",
    "fact_delivery_state_month",
    "avg_delivery_delay_days",
    "avg",
    "duration",
  ],
  [
    "state-pair-distance-avg",
    "州对平均运输距离",
    "fact_delivery_state_month",
    "avg_haversine_distance_km",
    "avg",
    "other",
  ],
] as const;
const metrics = metricDefinitions.map(([id, name, table, column, aggregation, dimension]) => ({
  metric_id: `ecommerce-${id}@1`,
  name,
  description: `${name}；按 ${table}.${column} 计算，必须遵守声明粒度与 fanout 策略。`,
  aliases: [name, id],
  table_id: table,
  column_id: `${table}.${column}`,
  aggregation,
  formula: null,
  grain: grain(table, table === "fact_delivery_state_month" ? "month" : "atomic"),
  unit: unit(dimension),
  time_domain: table.startsWith("fact_") ? timeDomain : null,
  time_column_id: table === "fact_order" ? "fact_order.purchased_at" : null,
  additivity: aggregation === "sum" || aggregation === "count" ? "additive" : "non-additive",
  null_policy: aggregation === "sum" || aggregation === "count" ? "coalesce-zero" : "exclude",
  fanout_policy: "preaggregate" as const,
  dependency_column_ids: [`${table}.${column}`],
  tags: ["ecommerce", table],
  analysis: {
    primary: id === "gmv-brl",
    priority: id === "gmv-brl" ? 100 : 0,
    missing_period_policy: "NULL" as const,
    seasonality: null,
    allowed_dimension_ids: [],
    capabilities: ["CHART_DATASET", "DATA_PROFILE"] as const,
    causal_role: null,
  },
}));

const dimensionDefinitions = [
  ["customer-state", "客户州", "dim_customer", "state", "text"],
  ["customer-city", "客户城市", "dim_customer", "city", "text"],
  ["seller-state", "卖家州", "dim_seller", "state", "text"],
  ["seller-city", "卖家城市", "dim_seller", "city", "text"],
  ["category", "商品类目", "dim_product", "category_name_english", "text"],
  ["product", "商品", "dim_product", "product_id", "text"],
  ["amazon-brand", "Amazon 品牌", "dim_amazon_product", "brand", "text"],
  ["amazon-category", "Amazon 主类目", "dim_amazon_product", "main_category", "text"],
  ["ebay-brand", "eBay 品牌", "dim_ebay_listing", "brand", "text"],
  ["ebay-os", "操作系统", "dim_ebay_listing", "operating_system", "text"],
  ["payment-type", "支付方式", "fact_payment", "payment_type", "text"],
  ["order-status", "订单状态", "fact_order", "order_status", "text"],
  ["purchase-date", "购买日期", "fact_order", "purchase_date", "date"],
  ["review-score", "评价星级", "fact_review", "review_score", "integer"],
  ["purchase-month", "购买月份", "fact_delivery_state_month", "purchase_month", "text"],
] as const;
const dimensions = dimensionDefinitions.map(([id, name, table, column, dataType]) => ({
  dimension_id: `ecommerce-${id}@1`,
  name,
  description: `${name}维度，来源 ${table}.${column}。`,
  aliases: [name, id],
  table_id: table,
  column_id: `${table}.${column}`,
  grain: grain(table, id === "purchase-month" ? "month" : "atomic"),
  data_type: dataType,
  sensitivity: "PUBLIC" as const,
  hierarchical: id.endsWith("state") || id === "purchase-date",
  parent_dimension_id: null,
  tags: ["ecommerce", "dimension"],
  analysis: { groupable: true, pivotable: true, causal_role: null },
}));

const relationshipDefinitions = [
  ["order-customer", "fact_order", "customer_id", "dim_customer", "customer_id", "many-to-one"],
  ["item-order", "fact_order_item", "order_id", "fact_order", "order_id", "many-to-one"],
  ["item-product", "fact_order_item", "product_id", "dim_product", "product_id", "many-to-one"],
  ["item-seller", "fact_order_item", "seller_id", "dim_seller", "seller_id", "many-to-one"],
  ["payment-order", "fact_payment", "order_id", "fact_order", "order_id", "many-to-one"],
  ["review-order", "fact_review", "order_id", "fact_order", "order_id", "many-to-one"],
  [
    "amazon-review-product",
    "fact_amazon_review",
    "asin",
    "dim_amazon_product",
    "asin",
    "many-to-one",
  ],
  [
    "product-category",
    "dim_product",
    "category_name",
    "dim_category",
    "category_name",
    "many-to-one",
  ],
] as const;
const relationships = relationshipDefinitions.map(
  ([id, left, leftColumn, right, rightColumn, cardinality]) => ({
    relationship_id: `ecommerce-${id}@1`,
    name: id,
    description: `${left}.${leftColumn} → ${right}.${rightColumn}`,
    kind: "physical" as const,
    left_table_id: left,
    left_column_ids: [`${left}.${leftColumn}`],
    right_table_id: right,
    right_column_ids: [`${right}.${rightColumn}`],
    cardinality,
    left_row_preservation: "required" as const,
    right_row_preservation: "optional" as const,
    proof_kind: "DDL_ENFORCED" as const,
    proof_detail: "PostgreSQL mart key and import quality receipt",
    tags: ["ecommerce", "join"],
    analysis: { join_allowed: true, fanout_closed: true, ontology_path: [] },
  }),
);

const entityNames = [
  "客户",
  "订单",
  "订单明细",
  "商品",
  "类目",
  "卖家",
  "支付",
  "评价",
  "配送",
  "地域",
  "日期",
  "Amazon 商品",
  "Amazon 评价",
  "eBay 刊登",
];
const termNames = [
  "成交总额",
  "订单量",
  "客单价",
  "件单价",
  "复购客户",
  "复购率",
  "活跃客户",
  "活跃卖家",
  "支付笔数",
  "分期支付",
  "评价分",
  "低评分",
  "好评率",
  "配送时长",
  "配送延迟",
  "准时送达",
  "延迟配送率",
  "运费",
  "运费率",
  "卖家履约",
  "类目满意度",
  "电子产品",
  "价格带",
  "价格四分位",
  "跨平台商品",
  "候选匹配",
  "匹配置信度",
  "人工审阅",
  "Amazon 标价",
  "eBay 刊登价",
  "Olist 成交价",
  "客户州",
  "卖家州",
  "州对",
  "购买月份",
  "运输距离",
  "Haversine 距离",
  "品牌",
  "内存容量",
  "固态硬盘容量",
  "订单状态",
  "支付方式",
  "商品重量",
  "商品体积",
  "评论文本",
  "数据快照",
];
const tables = [
  ...new Set([
    ...metrics.map(({ table_id }) => table_id),
    ...dimensions.map(({ table_id }) => table_id),
  ]),
];
const bundle = semanticSourceBundleSchema.parse({
  metadata: {
    bundle_version: "semantic-source-bundle@2",
    capability_profile: "U5_EXECUTABLE_SUBSET",
    bundle_id: "00000000-0000-4000-8000-00000000ec10",
    scope: {
      app_id: "00000000-0000-4000-8000-00000000da01",
      tenant_id: "00000000-0000-4000-8000-00000000ec11",
      environment: "template",
    },
    producer: { kind: "deterministic", id: "ecommerce-demo-bootstrap" },
    authority: {
      kind: "deterministic",
      id: "semantic-authority",
      policy_version: "ecommerce-semantic-policy@1.0.0",
    },
    authority_envelope: {
      kind: "PREVIEW",
      candidate_id: "00000000-0000-4000-8000-00000000ec20",
      working_revision: 1,
    },
    created_at: "2026-08-15T00:00:00Z",
    description: "AgenticDataBench E-commerce Demo 的 V2-only 语义运行时内容。",
  },
  formulas: [],
  metrics: metrics.toSorted((left, right) => left.metric_id.localeCompare(right.metric_id)),
  dimensions: dimensions.toSorted((left, right) =>
    left.dimension_id.localeCompare(right.dimension_id),
  ),
  relationships: relationships.toSorted((left, right) =>
    left.relationship_id.localeCompare(right.relationship_id),
  ),
  business_ontology: {
    domain: "ecommerce",
    owner: "Data Agent Demo",
    lifecycle: "active",
    entities: entityNames.map((name, index) => ({
      entity_id: `ecommerce-entity-${index + 1}@1`,
      name,
      description: `${name}业务实体`,
      aliases: [name],
      domain: "ecommerce",
      owner: "Data Agent Demo",
      lifecycle: "active",
      business_relationship_types: [],
    })),
    events: ["下单", "支付", "发货", "签收", "评价"].map((name, index) => ({
      event_id: `ecommerce-event-${index + 1}@1`,
      name,
      description: `${name}业务事件`,
      domain: "ecommerce",
      subject_entity_id: `ecommerce-entity-${index === 4 ? 8 : 2}@1`,
      event_type: name,
    })),
    terms: termNames.map((name, index) => ({
      term_id: `ecommerce-term-${index + 1}@1`,
      name,
      definition: `${name}：E-commerce Demo 中按 V2 指标、维度和数据质量规则解释的中文业务术语。`,
      domain: "ecommerce",
      aliases: [name],
    })),
  },
  physical_binding: {
    default_datasource_id: datasourceId,
    entries: [
      ...tables.map((table) => ({
        logical_object_id: table,
        logical_object_type: "table" as const,
        datasource_id: datasourceId,
        schema_name: "demo_adb_ecommerce_mart",
        table_name: table,
        column_name: null,
        binding_lifecycle: "active" as const,
        valid_from: "2026-08-15",
        valid_until: null,
      })),
      ...metrics.map((metric) => ({
        logical_object_id: metric.metric_id,
        logical_object_type: "metric" as const,
        datasource_id: datasourceId,
        schema_name: "demo_adb_ecommerce_mart",
        table_name: metric.table_id,
        column_name: physicalColumnName(metric.column_id),
        binding_lifecycle: "active" as const,
        valid_from: "2026-08-15",
        valid_until: null,
      })),
      ...dimensions.map((dimension) => ({
        logical_object_id: dimension.dimension_id,
        logical_object_type: "dimension" as const,
        datasource_id: datasourceId,
        schema_name: "demo_adb_ecommerce_mart",
        table_name: dimension.table_id,
        column_name: physicalColumnName(dimension.column_id),
        binding_lifecycle: "active" as const,
        valid_from: "2026-08-15",
        valid_until: null,
      })),
    ],
  },
  catalog_governance: {
    tables: tables.map((table) => ({
      table_id: table,
      table_name: table,
      description: `${table} mart table`,
      columns: [
        ...new Set([
          ...metrics.filter((item) => item.table_id === table).map((item) => item.column_id),
          ...dimensions.filter((item) => item.table_id === table).map((item) => item.column_id),
        ]),
      ].map((column_id) => ({
        column_id,
        nullable: true,
        data_type: "text",
        constraint_refs: [],
        description: `${column_id} governed source`,
      })),
      snapshot_currentness: {
        snapshot_timestamp: "2026-08-15T00:00:00Z",
        staleness_threshold_seconds: null,
      },
      catalog_fence: "adb-ecommerce-v1",
    })),
    data_quality_oracle_refs: [],
  },
});
await writeFile(output, `${JSON.stringify(bundle, null, 2)}\n`, "utf8");
console.log(
  JSON.stringify({
    output,
    metrics: metrics.length,
    dimensions: dimensions.length,
    relationships: relationships.length,
    entities: entityNames.length,
    terms: termNames.length,
  }),
);
