import { describe, expect, it } from "vitest";
import * as platform from "../../src/index.js";

describe("platform package public surface", () => {
  it("exports only production, scope-aware U2/U4/U6 entry points", () => {
    expect(Object.keys(platform).sort()).toEqual([
      "ArtifactWorkspaceError",
      "CatalogContractError",
      "MICROCREDITS_PER_CNY",
      "MICROCREDITS_PER_CREDIT",
      "Neo4jRelationshipIndexError",
      "PERSISTENCE_TRANSACTION_DIAGNOSTIC_CHANNEL",
      "POSTGRES_BIGINT_MAX",
      "PersistenceBoundaryError",
      "PythonSqlSandboxProtocolError",
      "adaptPgCatalogPool",
      "adaptPgPool",
      "addMicrocredits",
      "agentTeamStoreCommandSchema",
      "assertEcommerceBenchmarkReadOnlySql",
      "assertFalconBenchmarkReadOnlySql",
      "assertFalconDatabaseSchema",
      "buildAgentTeamStoreCommand",
      "calculateModelCost",
      "ceilRationalMicrocredits",
      "cnyAmountToMicrocredits",
      "comparePhysicalSchemaSnapshots",
      "containsPotentialPlaintextSecret",
      "createArtifactWorkspaceService",
      "createBillingGatedProvider",
      "createCacheNamespace",
      "createClamAvInstreamClient",
      "createCoordinatedSandboxPort",
      "createFileScanPort",
      "createFileSystemStorageClient",
      "createInMemoryRelationshipGraphAdapter",
      "createNeo4jRelationshipGraphAdapter",
      "createNeo4jRelationshipGraphAdapterFromEnvironment",
      "createPhysicalSchemaSnapshot",
      "createPostgresArtifactWorkspaceStore",
      "createPostgresCapabilityAuthority",
      "createPostgresCatalogScanner",
      "createPostgresControlledFixture",
      "createPostgresCreditLedgerRepository",
      "createPostgresDatasourceEgress",
      "createPostgresEcommerceBenchmarkExecutor",
      "createPostgresEffectiveConfigResolver",
      "createPostgresFalconBenchmarkExecutor",
      "createPostgresGreenfieldBootstrapReleaseAuthority",
      "createPostgresJobQueue",
      "createPostgresModelBillingRepository",
      "createPostgresOntologyPackageStore",
      "createPostgresOperationsAdminRepository",
      "createPostgresPricingControlRepository",
      "createPostgresPrivilegedGrantAuthority",
      "createPostgresProviderInvocationSmokeJob",
      "createPostgresProviderInvocationStore",
      "createPostgresProviderStaleMarkerRecoveryJob",
      "createPostgresRelationshipIndexStore",
      "createPostgresRepository",
      "createPostgresResearchAuthority",
      "createPostgresResearchResourceInvocation",
      "createPostgresRunControl",
      "createPostgresRunEventStore",
      "createPostgresRunQueue",
      "createPostgresSchemaSnapshotStore",
      "createPostgresSecretRefRepository",
      "createPostgresSemanticAuthoringQueue",
      "createPostgresSemanticAuthoringStore",
      "createPostgresSemanticCandidateCompileStore",
      "createPostgresSemanticExplorerReader",
      "createPostgresSemanticGraphStore",
      "createPostgresSemanticPortabilityRepository",
      "createPostgresTeamRunStore",
      "createPostgresText2SqlSandboxAuthority",
      "createPostgresWorkspaceAuthority",
      "createPostgresWorkspaceDataRepository",
      "createPostgresWorkspaceFiles",
      "createPublishedF9LifecycleService",
      "createPythonSqlSandboxClient",
      "createScopedUpstashCache",
      "createSensitiveExecutionArtifactAuthority",
      "createStorageNamespace",
      "createWorkspaceContentGcService",
      "createWorkspaceContentNamespace",
      "createWorkspaceContentOrphanGc",
      "creditAmountToMicrocredits",
      "microcreditsToCnyAmount",
      "microcreditsToCreditAmount",
      "neutralizeSpreadsheetFormula",
      "projectArtifactDocument",
      "providerInvocationSmokeClaimSchema",
      "providerInvocationSmokeProofSchema",
      "providerInvocationUnknownClassificationSchema",
      "renderArtifactExport",
      "roundHalfUpMicrocredits",
      "subtractMicrocredits",
      "withAppTransaction",
    ]);
  });

  it("does not expose process-local authorities or raw provider adapters", () => {
    expect(platform).not.toHaveProperty("createDeploymentRegistry");
    expect(platform).not.toHaveProperty("createLifecycleEvidenceAuthority");
    expect(platform).not.toHaveProperty("LifecycleRegistry");
    expect(platform).not.toHaveProperty("SecretRegistry");
    expect(platform).not.toHaveProperty("createDatasourceEgressPolicyRegistry");
    expect(platform).not.toHaveProperty("createUpstashRedisRestClient");
    expect(platform).not.toHaveProperty("createUpstashRedisRestClientFromEnv");
    expect(platform).not.toHaveProperty("startSingleExecutionNdjsonProcess");
    expect(platform).not.toHaveProperty("capabilityInputSchema");
    expect(platform).not.toHaveProperty("historicalDocumentSchema");
    expect(platform).not.toHaveProperty("ResearchAuthorityTransportError");
  });
});
