export enum SemanticGraphErrorCode {
  INVALID_GRAPH = "INVALID_GRAPH",
  DUPLICATE_IDENTITY = "DUPLICATE_IDENTITY",
  REGISTRY_MISSING = "REGISTRY_MISSING",
  REGISTRY_ENDPOINT_MISMATCH = "REGISTRY_ENDPOINT_MISMATCH",
  EDGE_FAMILY_MISMATCH = "EDGE_FAMILY_MISMATCH",
  EDGE_ATTRIBUTE_MISMATCH = "EDGE_ATTRIBUTE_MISMATCH",
  DANGLING_EDGE = "DANGLING_EDGE",
  EVIDENCE_NOT_FOUND = "EVIDENCE_NOT_FOUND",
  PHYSICAL_STRUCTURE_INVALID = "PHYSICAL_STRUCTURE_INVALID",
  FORMULA_SLOT_UNBOUND = "FORMULA_SLOT_UNBOUND",
  FORMULA_SLOT_DUPLICATE_BINDING = "FORMULA_SLOT_DUPLICATE_BINDING",
  FORMULA_SLOT_UNUSED = "FORMULA_SLOT_UNUSED",
  FORMULA_TYPE_CONFLICT = "FORMULA_TYPE_CONFLICT",
  UNIT_CONFLICT = "UNIT_CONFLICT",
  GRAIN_CONFLICT = "GRAIN_CONFLICT",
  FANOUT_CONFLICT = "FANOUT_CONFLICT",
  FORMULA_DEPENDENCY_CYCLE = "FORMULA_DEPENDENCY_CYCLE",
  DIMENSION_HIERARCHY_CYCLE = "DIMENSION_HIERARCHY_CYCLE",
  RUNTIME_COMPATIBILITY_AMBIGUOUS = "RUNTIME_COMPATIBILITY_AMBIGUOUS",
  RUNTIME_CAPABILITY_UNSUPPORTED = "RUNTIME_CAPABILITY_UNSUPPORTED",
  SYSTEM_MANAGED_MUTATION = "SYSTEM_MANAGED_MUTATION",
  PATCH_CONFLICT = "PATCH_CONFLICT",
  PATCH_DIGEST_MISMATCH = "PATCH_DIGEST_MISMATCH",
}

export interface SemanticGraphValidationIssue {
  readonly code: SemanticGraphErrorCode;
  readonly message: string;
  readonly entry_id?: string;
  readonly details: readonly string[];
}

export class SemanticGraphError extends Error {
  override readonly name = "SemanticGraphError";

  constructor(
    readonly code: SemanticGraphErrorCode,
    message: string,
    readonly details: readonly string[] = [],
  ) {
    super(message);
  }
}
